# OTT 고객 초기 데이터 정의
# customers는 list[dict] 형태로 저장합니다.
customers: list[dict] = [
    {
        "customer_id": "001",
        "name": "김민지",
        "age": 29,
        "gender": "F",
        "country": "KR",
        "plan": True,
        "last_watch_title": "오징어게임",
    },
    {
        "customer_id": "002",
        "name": "이준호",
        "age": 34,
        "gender": "M",
        "country": "KR",
        "plan": True,
        "last_watch_title": "더 글로리",
    },
    {
        "customer_id": "003",
        "name": "박서연",
        "age": 26,
        "gender": "F",
        "country": "KR",
        "plan": False,
        "last_watch_title": "킹덤",
    },
    {
        "customer_id": "004",
        "name": "최민수",
        "age": 41,
        "gender": "M",
        "country": "KR",
        "plan": True,
        "last_watch_title": "무빙",
    },
    {
        "customer_id": "005",
        "name": "정유진",
        "age": 31,
        "gender": "F",
        "country": "KR",
        "plan": True,
        "last_watch_title": "D.P.",
    },
    {
        "customer_id": "006",
        "name": "한지훈",
        "age": 24,
        "gender": "M",
        "country": "KR",
        "plan": False,
        "last_watch_title": "이상한 변호사 우영우",
    },
    {
        "customer_id": "007",
        "name": "윤서아",
        "age": 27,
        "gender": "F",
        "country": "KR",
        "plan": True,
        "last_watch_title": "스위트홈",
    },
    {
        "customer_id": "008",
        "name": "장도윤",
        "age": 38,
        "gender": "M",
        "country": "KR",
        "plan": True,
        "last_watch_title": "눈물의 여왕",
    },
    {
        "customer_id": "009",
        "name": "Emily Carter",
        "age": 27,
        "gender": "F",
        "country": "US",
        "plan": True,
        "last_watch_title": "Stranger Things",
    },
    {
        "customer_id": "010",
        "name": "Michael Lee",
        "age": 36,
        "gender": "M",
        "country": "US",
        "plan": True,
        "last_watch_title": "Wednesday",
    },
]


